/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mazewelcome;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author ae
 */
public class CreateProfile extends javax.swing.JFrame
{
    static boolean Create=false;

    boolean checkvalid(String c)
    {
        if(c.contains(".") || c.contains(";") || c.contains(":") || c.contains("!") || c.contains("?")||c.contains(","))
        {
            return false;
        }

        else
        {
            return true;
        } 
    }   
    /**
         * Creates new form CreateProfile
         */
    public CreateProfile() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() 
    {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        UsernameTxtfield = new javax.swing.JTextField();

        create = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setMaximumSize(new java.awt.Dimension(720, 472));
        setMinimumSize(new java.awt.Dimension(720, 172));
        setPreferredSize(new java.awt.Dimension(720, 472));
        setSize(new java.awt.Dimension(720, 472));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("       Create Profile");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 10, 180, 28);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("  username");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 110, 100, 29);

        UsernameTxtfield.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                UsernameTxtfieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTxtfield);
        UsernameTxtfield.setBounds(330, 100, 156, 36);

        create.setBackground(new java.awt.Color(204, 204, 204));
        create.setText("create");
        create.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        
        create.addActionListener(new java.awt.event.ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                createActionPerformed(evt);
            }
        });
        getContentPane().add(create);
        create.setBounds(320, 320, 140, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("create.jpg"));

        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 720, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTxtfieldActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_UsernameTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTxtfieldActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) 
    {//GEN-FIRST:event_createActionPerformed
        String username=UsernameTxtfield.getText();
        boolean chekexist=false;

        if (!username.equals("") && checkvalid(UsernameTxtfield.getText()))
        {
            File user=new File("Username.txt");
            try 
            {
                Scanner Reader=new Scanner(user);
                while(Reader.hasNextLine())
                {
                    String data=Reader.nextLine();
                    if(data.equals(username)){chekexist=true;}
                }
            }

            catch (FileNotFoundException e) 
            {
                JOptionPane.showMessageDialog(null, "nemishe");
            } 

            if(chekexist==false)
            {
                JOptionPane.showMessageDialog(rootPane, "The profile succesfully created !", "Succsfuly created", JOptionPane.INFORMATION_MESSAGE);
                Users ejra=new Users(username);
                Create=true;
                this.setVisible(false);
            }

            else
            { 
                JOptionPane.showMessageDialog(rootPane, "The Profile alreay exist", "eror", JOptionPane.WARNING_MESSAGE); 
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog(rootPane, "The username shouldn't be empty and shoud not include(.,;:!?)  ", "eror", JOptionPane.WARNING_MESSAGE);
        }
    // TODO add your handling code here:
    }
    //GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try 
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) 
            {
                if ("Nimbus".equals(info.getName())) 
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } 

        catch (ClassNotFoundException ex) 
        {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

        catch (InstantiationException ex) 
        {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

        catch (IllegalAccessException ex) 
        {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

        catch (javax.swing.UnsupportedLookAndFeelException ex) 
        {
            java.util.logging.Logger.getLogger(CreateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new CreateProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UsernameTxtfield;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
